# automatically generated by the FlatBuffers compiler, do not modify

# namespace: simple

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HashOutPut(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HashOutPut()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHashOutPut(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HashOutPut
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HashOutPut
    def Result(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from simple.HashResponse import HashResponse
            obj = HashResponse()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HashOutPut
    def ResultLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HashOutPut
    def ResultIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def HashOutPutStart(builder):
    builder.StartObject(1)

def Start(builder):
    HashOutPutStart(builder)

def HashOutPutAddResult(builder, result):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder, result):
    HashOutPutAddResult(builder, result)

def HashOutPutStartResultVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartResultVector(builder, numElems):
    return HashOutPutStartResultVector(builder, numElems)

def HashOutPutEnd(builder):
    return builder.EndObject()

def End(builder):
    return HashOutPutEnd(builder)
