# automatically generated by the FlatBuffers compiler, do not modify

# namespace: simple

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HashRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HashRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHashRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HashRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HashRequest
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # HashRequest
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HashRequest
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # HashRequest
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HashRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    HashRequestStart(builder)

def HashRequestAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    HashRequestAddData(builder, data)

def HashRequestStartDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDataVector(builder, numElems):
    return HashRequestStartDataVector(builder, numElems)

def HashRequestAddCount(builder, count):
    builder.PrependUint32Slot(1, count, 0)

def AddCount(builder, count):
    HashRequestAddCount(builder, count)

def HashRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return HashRequestEnd(builder)
