# automatically generated by the FlatBuffers compiler, do not modify

# namespace: simple

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HashResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HashResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHashResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HashResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HashResponse
    def UserData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HashResponse
    def HashData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HashResponseStart(builder):
    builder.StartObject(2)

def Start(builder):
    HashResponseStart(builder)

def HashResponseAddUserData(builder, userData):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(userData), 0)

def AddUserData(builder, userData):
    HashResponseAddUserData(builder, userData)

def HashResponseAddHashData(builder, hashData):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(hashData), 0)

def AddHashData(builder, hashData):
    HashResponseAddHashData(builder, hashData)

def HashResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return HashResponseEnd(builder)
