// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package simple

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HashRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsHashRequest(buf []byte, offset flatbuffers.UOffsetT) *HashRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HashRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishHashRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHashRequest(buf []byte, offset flatbuffers.UOffsetT) *HashRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HashRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHashRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HashRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HashRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HashRequest) Jobs(obj *HashJob, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *HashRequest) JobsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func HashRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HashRequestAddJobs(builder *flatbuffers.Builder, jobs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(jobs), 0)
}
func HashRequestStartJobsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func HashRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
