// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package simple

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HashResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsHashResponse(buf []byte, offset flatbuffers.UOffsetT) *HashResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HashResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishHashResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHashResponse(buf []byte, offset flatbuffers.UOffsetT) *HashResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HashResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHashResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HashResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HashResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HashResponse) UserData() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HashResponse) HashData() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func HashResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func HashResponseAddUserData(builder *flatbuffers.Builder, userData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(userData), 0)
}
func HashResponseAddHashData(builder *flatbuffers.Builder, hashData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(hashData), 0)
}
func HashResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
