// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package simple

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HashRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsHashRequest(buf []byte, offset flatbuffers.UOffsetT) *HashRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HashRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishHashRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHashRequest(buf []byte, offset flatbuffers.UOffsetT) *HashRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HashRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHashRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HashRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HashRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HashRequest) Data(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *HashRequest) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *HashRequest) Count() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HashRequest) MutateCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func HashRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func HashRequestAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func HashRequestStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func HashRequestAddCount(builder *flatbuffers.Builder, count uint32) {
	builder.PrependUint32Slot(1, count, 0)
}
func HashRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
